name: Run PlatformIO Tests

on:
  pull_request:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        pip install platformio
    
    - name: Verify PlatformIO version
      run: pio --version
    
    - name: Verify Arduino Core version
      run: pio pkg list

    - name: Run tests
      run: pio test -e native -vvv
